#!/usr/bin/env bash

# arm
if [[ "$(/usr/bin/uname -m)" == 'arm64' ]]; then
    alias x86='arch -x86_64 "$SHELL"'
else
    _osx_architecture()
    {
        declare arch="$(/usr/bin/uname -m)"
        if [[ "$arch" == 'x86_64' ]]; then
            echo 'x86'
        fi
    }
    RPROMPT='$(_osx_architecture)'
fi
