#!/usr/bin/env bash

# common package management
alias pki='brew install'
alias pks='brew search'
# alias pkf='' # nothing provides this... (could probably maintain a repo like xlocate for void does though)
alias pkl='brew ls'
pko()
{
    for package in $(brew ls); do
        packageSedEscaped="$(echo "$package" | sed -e 's/[\/&]/\\&/g')"
        brew ls "$package" | sed -e 's/^/'"$packageSedEscaped"': /' | grep "$package: $1"
    done
    true
}

# overrides
alias all-clear="tput reset && printf '\e[3J'"

alias dr='defaults read'
alias dw='defaults write'

# M1
# NOTE: only if current shell is running in arm mode
if [[ "$(/usr/bin/uname -m)" == 'arm64' ]]; then
    alias x86='arch -x86_64 /bin/zsh'
else
    # TODO: only want this is the machine is actually an M1
    _osx_architecture()
    {
        # TODO: only if we're actually running on an m1 mac
        declare arch="$(/usr/bin/uname -m)"
        if [[ "$arch" == 'x86_64' ]]; then
            echo 'x86'
        fi
    }
    RPROMPT='$(_osx_architecture)'
fi

# instead of having coreutils on the path, better than nothing...
alias b2sum='gb2sum'
alias base32='gbase32'
alias base64='gbase64'
alias basename='gbasename'
alias basenc='gbasenc'
alias cat='gcat'
alias chcon='gchcon'
alias chgrp='gchgrp'
alias chmod='gchmod'
alias chown='gchown'
alias chroot='gchroot'
alias cksum='gcksum'
alias comm='gcomm'
alias cp='gcp'
alias csplit='gcsplit'
alias cut='gcut'
alias date='gdate'
alias dd='gdd'
alias df='gdf'
alias dir='gdir'
alias dircolors='gdircolors'
alias dirname='gdirname'
alias du='gdu'
alias echo='gecho'
alias env='genv'
alias expand='gexpand'
alias expr='gexpr'
alias factor='gfactor'
alias 'false'='gfalse'
alias fmt='gfmt'
alias fold='gfold'
alias groups='ggroups'
alias head='ghead'
alias hostid='ghostid'
alias id='gid'
alias install='ginstall'
alias join='gjoin'
alias kill='gkill'
alias link='glink'
alias ln='gln'
alias logname='glogname'
alias ls='gls'
alias md5sum='gmd5sum'
alias mkdir='gmkdir'
alias mkfifo='gmkfifo'
alias mknod='gmknod'
alias mktemp='gmktemp'
alias mv='gmv'
alias nice='gnice'
alias nl='gnl'
alias nohup='gnohup'
alias nproc='gnproc'
alias numfmt='gnumfmt'
alias od='god'
alias paste='gpaste'
alias pathchk='gpathchk'
alias pinky='gpinky'
alias pr='gpr'
alias printenv='gprintenv'
alias printf='gprintf'
alias ptx='gptx'
alias pwd='gpwd'
alias readlink='greadlink'
alias realpath='grealpath'
alias rm='grm'
alias rmdir='grmdir'
alias runcon='gruncon'
alias seq='gseq'
alias sha1sum='gsha1sum'
alias sha224sum='gsha224sum'
alias sha256sum='gsha256sum'
alias sha384sum='gsha384sum'
alias sha512sum='gsha512sum'
alias shred='gshred'
alias shuf='gshuf'
alias sleep='gsleep'
alias sort='gsort'
alias split='gsplit'
alias stat='gstat'
alias stdbuf='gstdbuf'
alias stty='gstty'
alias sum='gsum'
alias sync='gsync'
alias tac='gtac'
alias tail='gtail'
alias tee='gtee'
alias test='gtest'
alias timeout='gtimeout'
alias touch='gtouch'
alias tr='gtr'
alias 'true'='gtrue'
alias truncate='gtruncate'
alias tsort='gtsort'
alias tty='gtty'
alias uname='guname'
alias unexpand='gunexpand'
alias uniq='guniq'
alias unlink='gunlink'
alias uptime='guptime'
alias users='gusers'
alias vdir='gvdir'
alias wc='gwc'
alias who='gwho'
alias whoami='gwhoami'
alias yes='gyes'
