#!/usr/bin/env bash

pko()
{
    for package in $(brew ls); do
        packageSedEscaped="$(echo "$package" | sed -e 's/[\/&]/\\&/g')"
        brew ls "$package" | sed -e 's/^/'"$packageSedEscaped"': /' | grep "$package: $1"
    done
    true
}

# M1
# NOTE: only if current shell is running in arm mode
if [[ "$(/usr/bin/uname -m)" == 'arm64' ]]; then
    alias x86='arch -x86_64 /bin/zsh'
else
    _osx_architecture()
    {
        declare arch="$(/usr/bin/uname -m)"
        if [[ "$arch" == 'x86_64' ]]; then
            echo 'x86'
        fi
    }
    RPROMPT='$(_osx_architecture)'
fi
