#!/usr/bin/env bash

declare brew_prefix="$(brew --prefix)"
export PATH="${brew_prefix}/opt/coreutils/libexec/gnubin:${brew_prefix}/opt/python@3.8/bin:${PATH}"
unset brew_prefix

# TODO: probably want to move this to guarantee that the PATH is final
# NOTE: this sets the path for normal osx applications (ie. Sublime) which otherwise get the system default path
launchctl setenv PATH "$PATH"
