#!/usr/bin/env bash

# brew
if [[ -x /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
    export PATH="${HOMEBREW_PREFIX}/opt/coreutils/libexec/gnubin:${HOMEBREW_PREFIX}/opt/python@3.8/bin:${PATH}"
fi

# TODO: probably want to move this to guarantee that the PATH is final
# NOTE: this sets the path for normal osx applications (ie. Sublime) which otherwise get the system default path
launchctl setenv PATH "$PATH"
