#!/usr/bin/env zsh

if command-exists kubectl; then
    source <(\kubectl completion zsh)
fi

if command-exists dollarino; then
    eval "$(_DOLLARINO_COMPLETE=source_zsh dollarino)"
fi

. source-if-exists "$PYENV_ROOT/completions/pyenv.zsh"
