#!/usr/bin/env bash

if command-exists kubectl; then
    source <(\kubectl completion bash)
fi

if command-exists dollarino; then
    eval "$(_DOLLARINO_COMPLETE=source dollarino)"
fi

. source-if-exists "${PYENV_ROOT}/completions/pyenv.bash"
