sources:
  - .
  - ../dotfiles-private
plugins:
  - ../nk-plugins/files
  - ../nk-plugins/sudoers
  - ../nk-plugins/git-repo
  - ../nk-plugins/macos-hide
  - ../nk-plugins/macos-show
  - ../nk-plugins/macos-pmset
  - ../nk-plugins/macos-defaults
  - ../nk-plugins/macos-plist-merge
  - ../nk-plugins/macos-night-shift
  - ../nk-plugins/macos-terminal-theme
  - ../nk-plugins/macos-default-programs
  - ../nk-plugins/nix-cli
  - ../nk-plugins/brew
  - ./plugins/neovim-vim-plug
