sources:
  - .
  # TODO: merge these once nk is prepared to support sources in plugins
  # - ../dotfiles-private
plugins:
  - ../nk-plugins/files
  - ../nk-plugins/sudoers
  - ../nk-plugins/macos-hide
  - ../nk-plugins/macos-show
  # - ../nk-plugins/macos-pmset # TODO: temp
  - ../nk-plugins/macos-defaults
  - ../nk-plugins/macos-night-shift
  - ../nk-plugins/macos-terminal-theme
  # - ../nk-plugins/macos-default-programs # TODO: temp
  - ../nk-plugins/brew
