extends: default

rules:
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
  document-start: false
  line-length:
    max: 120
  comments:
    min-spaces-from-content: 1
  quoted-strings:
    required: only-when-needed
