files:
  - source: home
    destination: ~/
    link_files: true

# neovim
# ---
# files:
#   - source: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#     destination: ~/.local/share/nvim/site/autoload/plug.vim

# TODO: when above changes?
# nvim --headless +PlugInstall +qall

# TODO: speedcrunch

---
when: os in ["macos", "linux"]

sudoers:
  mode: passwordless # TODO: passwordless | touch id
  defaults: |
    # Don't keep HOME (that's super obnoxious)
    Defaults env_keep -= "HOME"
    # But do keep PATH so we can run our commands as root
    Defaults exempt_group = {{ user }}

---
when: os == "macos"

files:
  - source: files/karabiner.json
    destination: ~/.config/karabiner/karabiner.json
