when: os in ["macos", "linux"]

files:
  - source: home
    destination: ~/
    link_files: true

neovim.vim-plug:

git.repo:
  - source: https://github.com/robbyrussell/oh-my-zsh.git
    destination: ~/.oh-my-zsh

sudoers:
  mode: passwordless
  defaults: |
    # Don't keep HOME (that's super obnoxious)
    Defaults env_keep -= "HOME"
    # But do keep PATH so we can run our commands as root
    Defaults exempt_group = {{ user }}

shell.values:
  - destination: ~/.shared_profile.d/nk-vars
    values:
      DOTFILES_MACHINE: "{{ machine }}"
    export: true

---
when: os == "macos"

files:
  - source: files/karabiner.json
    destination: ~/.config/karabiner/karabiner.json
