#!/usr/bin/env bash

# git
if command-exists git; then
    alias git-diff-shortstat='git diff --shortstat'
    alias git-assume-unchanged='git update-index --assume-unchanged'
    alias git-no-assume-unchanged='git update-index --no-assume-unchanged'
    alias git-list-assume-unchanged='git ls-files -v | grep "^[[:lower:]]"'
    git-repos-exec()
    {
        find . -name .git -type d -prune -print0 | while IFS= read -r -d $'\0' dotgit; do
            pushd "$dotgit/../" > /dev/null
            eval "$@"
            popd > /dev/null
        done
    }
fi

# Kubernetes
if command-exists kubectl; then
    alias k=kubectl
    krun() {
        if [[ "$#" -lt 1 ]]; then
            echo 'usage: krun <image> [<kubectl-options-or-commands>...]' 1>&2
            return 1
        fi

        declare image="$1"
        declare -a args=()
        declare has_command='false'

        # TODO: surely there's a less messy way of doing all this
        # krun redis
        # krun redis sh
        # krun redis -- sh
        # krun redis -n istio-system
        # krun redis -n istio-system sh # expected to break
        # krun redis -n istio-system -- sh
        if [[ "$#" -ge 2 && "$2" != '-'* ]]; then
            # has a command first: at least one arg after image, and it's not an option
            # ie. krun redis sh
            args+=('--')
            args+=("${@:2}")
        else
            # has args or separator first
            # ie. krun redis -- sh
            # ie. krun redis -n istio-system
            for arg in "${@:2}"; do
                args+=("$arg")
                # NOTE: technically there may not be a command after the --, but tbh who gonna write -- at the end and nothing after it... :p (laziness)
                if [[ "$arg" == '--' ]]; then
                    has_command='true'
                fi
            done

            # add command after args
            if [[ "$has_command" != 'true' ]]; then
                args+=('--' 'bash')
            fi
        fi

        # run
        kubectl --generator=run-pod/v1 run william-testing-$(epoch) --rm -it --image "$image" "${args[@]}"
    }
fi
if command-exists kubectx; then
    alias ktx=kubectx
fi

# Docker
if command-exists docker-compose; then
    alias dc=docker-compose
fi

# Vagrant
if command-exists vagrant; then
    alias vag='vagrant'
fi

# Terraform
if command-exists terraform; then
    alias tf='terraform'
fi

# Salt
if command-exists salt-call; then
    alias sc='sudo salt-call'
fi

# BPython
if command-exists bpython2; then
    alias bp='bpython2'
    alias bp2='bpython2'
fi
if command-exists bpython; then
    alias bp3='bpython'
fi

# Nim
if command-exists nim; then
    alias nim='nim --nimcache=.nimcache'
fi

# SystemD
if command-exists switch-to-systemd; then
    alias switch-to-systemd='. switch-to-systemd'
fi

# XEV Keys
if command-exists xev; then
    alias xev='xev -rv -name xev-is-special'
    alias xev-keys="xev | grep -A2 --line-buffered '^KeyRelease' | sed -n '/keycode /s/^.*keycode \([0-9]*\).* (.*, \(.*\)).*$/\1 \2/p'"
fi
# xprop
if command-exists xprop; then
    alias xprop="xprop | grep -v ^$'\t[^\w\t]' | tr -s '\n'"
    # window info
    alias window-info='xprop; xwininfo'
fi

if command-exists scanelf; then
    symbol-provider()
    {
        scanelf -l -s "$1" | grep "$1"
    }
fi

if command-exists cmake; then
    alias cmake-debug='cmake -DCMAKE_BUILD_TYPE=Debug'
    alias cmake-release='cmake -DCMAKE_BUILD_TYPE=Release'
fi

# Include lf commands
. source-if-exists ~/projects/lf/commands.sh ~/projects/lf

# Theos
if [[ -d /opt/theos ]]; then
    export THEOS=/opt/theos
fi

# gpg
export GPG_TTY=$(tty)
