#!/usr/bin/env bash

# pentible-infrastructure
if [[ -d ~/Dropbox/Projects/pentible-infrastructure/scripts ]]; then
    for script in ~/Dropbox/Projects/pentible-infrastructure/scripts/*.sh; do
        declare name="$(basename ${script/.sh/})"
        alias "pi-$name"="$script"
    done
fi
