#!/usr/bin/env bash

# Pacman scripts
if command-exists pacman && command-exists makepkg; then
    alias pkgbuild-install='makepkg -f && sudo pacman -U *.pkg.tar.xz'
fi

# apt
if command-exists apt-file; then
    alias apt-file='sudo apt-file'
fi

export FILEMANAGER="spacefm"
