# theme
foreground #fafaf0
background #282921
cursor #fafaf0

color0 #282921
color1 #ff2070
color2 #b0ff11
color3 #ffc16a
color4 #56e4ff
color5 #ae81ff
color6 #91ffef
color7 #fafaf0
color8 #7b7558
color9 #ff2070
color10 #b0ff11
color11 #ffc16a
color12 #56e4ff
color13 #ae81ff
color14 #91ffef
color15 #faf9f4

selection_background #fafaf0
selection_foreground #282921
active_tab_background #7b7558
active_tab_foreground #282921
active_border_color #7b7558
inactive_tab_background #282921
inactive_tab_foreground #7b7558
inactive_border_color #7b7558
url_color #56e4ff

#
font_family Inconsolata
bold_font        Inconsolata Bold
italic_font      auto
bold_italic_font auto
font_size 16
placement_strategy top-left

enable_audio_bell no
