#!/usr/bin/env bash

case $TERM in
    xterm*|rxvt*|alacritty)
        # tabs = 4 spaces
        if type setterm >/dev/null 2>&1; then
            TERM=linux setterm -regtabs 4
        elif type tabs >/dev/null 2>&1; then
            tabs -4
        fi

        precmd()
        {
            declare title="${PWD/#$HOME/"~"} - $USER@`hostname`"
            echo -ne "\033]0;$title\007" 1>&2
        }
        preexec()
        {
            # These cause flickering of the title otherwise
            command="${1/%\ */}"
            case "$command" in
                cd|pushd|popd)
                    return
                ;;
            esac

            declare title="$1 - $USER@`hostname`"
            echo -ne "\033]0;$title\007" 1>&2
        }
esac
