#!/usr/bin/env bash

# who provides file
alias pkf='xlocate'
# update who provides file
alias pkfu='xlocate -S'
# who provides local file
alias pkfo='xbps-query -o'
# list files of local pkg
alias pkl='xbps-query -f'
# info for local pkg
alias pkq='xbps-query -i'
