#!/usr/bin/env bash

# common package management
# install pkgs
alias pki='sudo xbps-install -Sy'
# search pkgs
alias pks='xbps-query -Rs'
# update pkgs
alias pku='sudo xbps-install -Suv'

# who provides file
alias pkf='xlocate'
# update who provides file
alias pkfu='xlocate -S'
# who provides local file
alias pkfo='xbps-query -o'
# list files of local pkg
alias pkl='xbps-query -f'
# info for local pkg
alias pkq='xbps-query -i'
