#!/usr/bin/env bash

# Systemd update user path (Enables me to use my custom commands from systemd run services/scripts)
if command-exists systemctl; then
	systemctl --user import-environment PATH
fi
