#!/usr/bin/env zsh

# NOTE: unfortunately this has to be separate from bash because bash doesn't like it quoted/escaped the ?, and zsh doesn't like it unquoted/unescaped
'?'()
{
    functions "$1" 2>/dev/null || alias "$1" 2>/dev/null || type -a "$1"
}
