#!/usr/bin/env zsh

# Key Bindings
# TODO: https://superuser.com/questions/197813/cycle-through-matches-in-zsh-history-incremental-pattern-search-backward
# TODO: I continue to hate the state of keybindings

# NOTE: run `bindkey` to see all keybindings

bindkey -e
if [[ "$OSTYPE" == darwin* ]]; then
    # TODO: Consider getting osx version with `sw_vers -productName && sw_vers -productVersion` or maybe just get os if no distro...
    distro="macos"
elif command-exists lsb_release; then
    distro="$(lsb_release -i -s)"
fi
distro="$distro:l"

case "$TERM" in
xterm*)

	case "$distro" in
	ubuntu)
		bindkey '\e[1;5C' forward-word
		bindkey '\e[1;5D' backward-word

		bindkey '^H' backward-kill-word
		bindkey '\e[3;5~' kill-word
		;;
	arch)
		bindkey  "\e[H"     beginning-of-line
		bindkey  "\e[F"      end-of-line

		bindkey '\e[1;5C' forward-word
		bindkey '\e[1;5D' backward-word

		bindkey '^?' backward-kill-word
		bindkey '\e[3;5~' kill-word

		bindkey '\e[3~' delete-char
		;;
	macos)
        bindkey '\e^[OA'   beginning-of-line
        bindkey '\e^[OB'   end-of-line
        ;;
    *)
        ;;
	esac
	;;
rxvt-unicode*)
	bindkey '^[Oc' forward-word
	bindkey '^[Od' backward-word
	bindkey '^[[3^' kill-word
	bindkey '^H' backward-kill-word
	;;
*)
	# bindkey  "\e[H"     beginning-of-line
	# bindkey  "\e[F"      end-of-line

	# bindkey '\e[C' forward-word
	# bindkey '\e[D' backward-word

	bindkey '^H' backward-kill-word
	# bindkey '\e[3~' kill-word
	;;
esac
