#!/usr/bin/env bash

if [[ -d "$HOME/.local/share/umake/swift/swift-lang/usr/bin" ]]; then
    export PATH="$HOME/.local/share/umake/swift/swift-lang/usr/bin:${PATH}"
fi

if [[ -d "/opt/android-sdk" ]]; then
    export ANDROID_HOME=/opt/android-sdk
fi

# Systemd update user path (Enables me to use my custom commands from systemd run services/scripts)
# TODO: Move this so it's always run last...
if command-exists systemctl; then
    __environ_sleuth()
    {
        # NOTE: this finds env vars for other processes and exports them here
        # - I hate this, but what else am I to do?

        declare filter="$1"

        while read -r pid; do
            if sudo egrep -q '^('"$filter"')=' "/proc/$pid/environ" 2>/dev/null; then
                eval export $(sudo cat /proc/$pid/environ 2>/dev/null | tr '\0' '\n' | egrep '^('"$filter"')=')
                break
            fi
        done < <(pgrep -u "$USER")
    }

    # get required env vars
    __environ_sleuth "DBUS_SESSION_BUS_ADDRESS"

    systemctl --user import-environment PATH
fi
