#!/usr/bin/env bash

export ANDROID_HOME="${HOME}/.android/sdk"
# TODO: as needed
# export PATH="${ANDROID_HOME}/emulator:${PATH}"
# export PATH="${ANDROID_HOME}/tools:${PATH}"
export PATH="${ANDROID_HOME}/tools/bin:${PATH}"
export PATH="${ANDROID_HOME}/platform-tools:${PATH}"

if command-exists dbus-launch; then
    export $(dbus-launch)
fi
