<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>todo</string>
        <string>txt</string>
    </array>
    <key>name</key>
    <string>Note</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>^\s*#.*</string>
            <key>name</key>
            <string>comment.line.note</string>
        </dict>
        <dict>
            <key>match</key>
            <string>^\s*x\s+.*</string>
            <key>name</key>
            <string>entity.name.function.note</string>
        </dict>
        <dict>
            <key>match</key>
            <string>^\s*\?\s+.*</string>
            <key>name</key>
            <string>support.function.note</string>
        </dict>
        <dict>
            <key>match</key>
            <string>^\s*~\s+.*</string>
            <key>name</key>
            <string>support.constant.note</string>
        </dict>
        <dict>
            <key>match</key>
            <string>^\s*%\s+.*</string>
            <key>name</key>
            <string>string.note</string>
        </dict>
        <dict>
            <key>match</key>
            <string>^\s*-\s+.*</string>
            <key>name</key>
            <string>variable.parameter.note</string>
        </dict>
        <dict>
            <key>match</key>
            <string>^\s*!\s+.*</string>
            <key>name</key>
            <string>keyword.note</string>
        </dict>
        <dict>
            <key>match</key>
            <string>^\s*!!\s+.*</string>
            <key>name</key>
            <string>invalid.illegal.note</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.note</string>
    <key>uuid</key>
    <string>d4cc42b4-8293-45f2-a7d6-5ec2e349b6c8</string>
</dict>
</plist>
