---
when:
  - platform not in ['windows']

files:
  - ~/*
idk:
  - |
    me
    you

packages:
  - build-essential
  - git
  - gnupg

# TODO: fix parsing for converting misc types to arrays of 1
# hostname: server-idk

---
when:
  - platform not in ['windows']

packages:
  - godot
  - kubectx

groups:
  - docker
  # OR
  - name: docker
    system: true
    is_member: true
---
