#!/usr/bin/env bash

# redeclare existing command_not_found_handle
read -r -d '' orig_command_not_found_handle << EOF
orig_command_not_found_handle()
$(if declare -f command_not_found_handle >/dev/null 2>&1; then
    declare -f command_not_found_handle | tail -n +2
else
    # handle no original defined
    echo '{ :; }'
fi)
EOF

eval "$orig_command_not_found_handle"

# TODO: figure out for zsh as well? not sure if this'll just work, obvs would also need to modify the orig_* stuff above
# command_not_found_handler()
# {
#     command_not_found_handle "$@"
# }

command_not_found_handle()
{
   declare cmd="$1"

   for full_command in "${cmd}.exe" "${cmd}.com" "${cmd}.bat"; do
       if type "$full_command" >/dev/null 2>&1; then
           "$full_command" "${@:2}"
           return
       fi
   done

   orig_command_not_found_handle "$@"
}
