#!/usr/bin/env zsh

emulate sh -c 'source /etc/profile'

# mainly intended for osx: system-wide environment settings for zsh(1)
if [ -x /usr/libexec/path_helper ]; then
    eval `/usr/libexec/path_helper -s`
fi
