#!/usr/bin/env bash

set -e

forrealz(){ realpath "$@" 2>/dev/null || readlink -f "$@"; }
srcDir="$(dirname "$(forrealz "${BASH_SOURCE[0]}")")"

# download and run
if [[ "$srcDir" == '.' ]]; then
	tmp=$(mktemp -d)

	cleanup()
	{
	    [[ -f "$tmp" ]] && rm -rf "$tmp"
	}
	trap cleanup EXIT

	# download
	curl -sL 'https://github.com/ciiqr/config/archive/master.zip' -o "$tmp/config.zip"
	unzip -qq "$tmp/config.zip" -d "$tmp"

	# install
	"$tmp/config-master/scripts/install" "$@" --copy
	exit "$?"
fi

. "$srcDir/include/common.sh"

# TODO: params:
# - link
link="true"
# TODO: if --copy is specified, it resets link to false
# - copy
# link="false"
# - ConfigDir
# TODO: no trailing slash!
configDir="/config"
# - PrivateConfigDir
# TODO: no trailing slash!
privateConfigDir="/config-private"
# - SaltDir
saltDir="/etc/salt"
# - Roles
roles="default "
# - Force
# TODO: add prompt for dangerous things

ensureRoot

srcRoot="${srcDir%/scripts}"

if [[ "$srcRoot" -ef "$configDir" ]]; then
	echo "running from config directory already"
else
	rm -rf "$configDir"
	if [[ "$link" == "true" ]]; then
		ln -sf "$srcRoot" "$configDir"
	else
		cp -r "$srcRoot" "$configDir"
	fi
fi

# bootstrap salt
# TODO: consider support for salt in editable mode... (though, maybe handle that outside of this script... maybe just don't do anything if salt is already installed... just consider then how to also support upgrading salt...)
# TODO: does this script work for osx?
curl -sL https://bootstrap.saltstack.com | sudo sh -s -- -X stable 2017.7

"$srcDir/setup-salt" --configDir "$configDir" --privateConfigDir "$privateConfigDir" --saltDir "$saltDir" --roles "$roles"

"$srcDir/provision"
