#!/usr/bin/env bash

set -e

forrealz(){ realpath "$@" 2>/dev/null || readlink -f "$@" 2>/dev/null || perl -e 'use File::Basename; use Cwd "abs_path"; print abs_path(@ARGV[0]);' -- "$@"; }
srcDir="$(dirname "$(forrealz "${BASH_SOURCE[0]}")")"

. "$srcDir/include/common.sh"

parse_cli_args "$@" || usage "$0"

ensureRoot

# install dependencies
if [[ "$OSTYPE" == darwin* ]]; then
    # cli tools
    if ! xcode-select -p >/dev/null; then
        xcode-select --install
    fi

    # primary user
    if [[ -z "$primaryUser" ]]; then
        primaryUser="$(salt-call grains.get primaryUser --out newline_values_only || true)"
        if [[ -z "$primaryUser" ]]; then
            primaryUser="$(logname)"
        fi
    fi

    # brew
    su "$primaryUser" <<'EOF'
    if ! which brew >/dev/null; then
        # install
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

        # update path
        eval "$(/opt/homebrew/bin/brew shellenv)"
    fi
EOF

    # Rosetta
    if [[ ! -f "/Library/Apple/System/Library/LaunchDaemons/com.apple.oahd.plist" ]]; then
        /usr/sbin/softwareupdate --install-rosetta --agree-to-license
    fi
fi

# bootstrap salt
download https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh \
    | sh -s -- -X -d -x python3 stable

# update path with salt commands
if [[ "$OSTYPE" == darwin* ]]; then
    if [ -x /usr/libexec/path_helper ]; then
        eval `/usr/libexec/path_helper -s`
    fi
fi

"$srcDir/setup-salt" "$@"

"$srcDir/provision"
