#!/usr/bin/env bash

set -e

forrealz(){ realpath "$@" 2>/dev/null || readlink -f "$@" 2>/dev/null || perl -e 'use File::Basename; use Cwd "abs_path"; print abs_path(@ARGV[0]);' -- "$@"; }
srcDir="$(dirname "$(forrealz "${BASH_SOURCE[0]}")")"

# download and run
if [[ "$srcDir" == '.' ]]; then
    tmp=$(mktemp -d)

    cleanup()
    {
        [[ -f "$tmp" ]] && rm -rf "$tmp"
    }
    trap cleanup EXIT

    if type curl >/dev/null 2>&1; then
        download_cmd="curl -sL"
    elif type wget >/dev/null 2>&1; then
        download_cmd="wget -O -"
    fi

    if [[ -z "$download_cmd" ]]; then
        echo "no download command found" 1>&2
        exit 1
    fi

    # download
    $download_cmd 'https://github.com/ciiqr/config/archive/master.zip' -o "$tmp/config.zip"
    unzip -qq "$tmp/config.zip" -d "$tmp"

    # install
    "$tmp/config-master/scripts/install" "$@" --copy

    exit
fi

. "$srcDir/include/common.sh"

parse_cli_args "$@" || usage "$0"

ensureRoot


srcRoot="${srcDir%/scripts}"

if [[ "$srcRoot" -ef "$configDir" ]]; then
    echo "running from config directory already"
else
    if [[ -e "$configDir" ]]; then
        confirm "This will delete the file located at: $configDir"
    fi
    rm -rf "$configDir"
    if [[ "$link" == "true" ]]; then
        ln -sf "$srcRoot" "$configDir"
    else
        cp -r "$srcRoot" "$configDir"
    fi
fi

# bootstrap salt
if [[ "$OSTYPE" == darwin* ]]; then
    # cli tools
    if ! xcode-select -p >/dev/null; then
        xcode-select --install
    fi

    # primary user
    if [[ -z "$primaryUser" ]]; then
        primaryUser="$(salt-call grains.get primaryUser --out newline_values_only || true)"
        if [[ -z "$primaryUser" ]]; then
            primaryUser="$(logname)"
        fi
    fi

    # brew
    su "$primaryUser" <<EOF
    if ! which brew >/dev/null; then
        echo | /usr/bin/ruby -e "\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    # salt
    # source: https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/salt.rb
    brew install --force --build-from-source "$srcRoot/salt/install/osx/salt.rb"
EOF
else
    if grep -q '^ID=arch$' /etc/os-release 2>/dev/null; then
        salt_bootstrap_args="git v2018.3.2"
    else
        salt_bootstrap_args="stable 2018.3.2"
    fi

    get_download_cmd
    $download_cmd https://bootstrap.saltstack.com | sh -s -- -X $salt_bootstrap_args
fi

"$srcDir/setup-salt" "$@"

"$srcDir/provision"
