#!/usr/bin/env bash

set -e

forrealz(){ realpath "$@" 2>/dev/null || readlink -f "$@" 2>/dev/null || perl -e 'use File::Basename; use Cwd "abs_path"; print abs_path(@ARGV[0]);' -- "$@"; }
srcDir="$(dirname "$(forrealz "${BASH_SOURCE[0]}")")"

. "$srcDir/include/common.sh"

notify="$1"

ensureRoot

cleanup()
{
    if [[ -n "$notify" ]]; then
        if [[ "$success" == "true" ]]; then
            status="done"
        else
            status="failed"
        fi
        notify "config update" "$status"
    fi
}
trap cleanup EXIT

# started
[[ -n "$notify" ]] && notify "config update" "started"

# get repo's to update
configDir="$(salt-call grains.get configDir --out newline_values_only)"
privateConfigDir="$(salt-call grains.get privateConfigDir --out newline_values_only)"

# update repo's
tryGitUpdate "$privateConfigDir"
tryGitUpdate "$configDir"

# re-install
"$configDir/scripts/install"

# NOTE: this must be the very last thing, so we can check it in cleanup
success=true
