[general]
live_config_reload = true

# theme
[colors.primary]
background = "#292524"
foreground = "#F5F5F4"
[colors.cursor]
text = "CellBackground"
cursor = "#F5F5F4"
[colors.normal]
black = "#282921"
red = "#FF2070"
green = "#B0FF11"
yellow = "#FFC16A"
blue = "#56E4FF"
magenta = "#AE81FF"
cyan = "#91FFEF"
white = "#F5F5F4"
[colors.bright]
black = "#7B7558"
red = "#FF2070"
green = "#B0FF11"
yellow = "#FFC16A"
blue = "#56E4FF"
magenta = "#AE81FF"
cyan = "#91FFEF"
white = "#FAF9F4"

# font
[font]
size = 16
normal = { family = "Inconsolata", style = "Regular" }
bold = { family = "Inconsolata", style = "Bold" }
# TODO: inconsolata doesn't have italics...
# italic = { family = "Inconsolata", style = "Condensed Light" }
# bold_italic = { family = "Inconsolata", style = "Condensed Bold" }

# misc
[[hints.enabled]]
command         = "open"
# On Windows
# command       = { program = "cmd", args = [ "/c", "start",  "" ] }
hyperlinks      = true
post_processing = true
persist         = false
mouse.enabled   = true
mouse.mods      = "Control"
# binding         = { key = "O", mods = "Control|Shift" }
regex           = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\\u{0000}-\\u{001F}\\u{007F}-\\u{009F}<>\"\\s{-}\\^⟨⟩`\\\\]+"
