[general]
live_config_reload = true

[colors.primary]
background = "#282921"
foreground = "#fafaf0"

[colors.cursor]
text = "CellBackground"
cursor = "#fafaf0"

[colors.normal]
black = "#282921"
red = "#ff2070"
green = "#b0ff11"
yellow = "#ffc16a"
blue = "#56e4ff"
magenta = "#ae81ff"
cyan = "#91ffef"
white = "#fafaf0"

[colors.bright]
black = "#7b7558"
red = "#ff2070"
green = "#b0ff11"
yellow = "#ffc16a"
blue = "#56e4ff"
magenta = "#ae81ff"
cyan = "#91ffef"
white = "#faf9f4"

[font]
size = 16
normal = { family = "Inconsolata", style = "Regular" }
bold = { family = "Inconsolata", style = "Bold" }
# TODO: inconsolata doesn't have italics...
# italic = { family = "Inconsolata", style = "Condensed Light" }
# bold_italic = { family = "Inconsolata", style = "Condensed Bold" }
