vim.cmd.highlight "clear"
vim.opt.background = "dark"
vim.g.colors_name = "okaio"
-- TODO: merge with kaio propa
local highlights = {
    ["@attribute.sql"] = { fg = "#DB2979" },
    ["@constant.builtin"] = { fg = "#A689FA" },
    ["@function.builtin"] = { fg = "#67E8F9" },
    ["@import_type"] = { fg = "#DB2979", nocombine = true },
    ["@joker_baby"] = { fg = "#DB2979" },
    ["@jsx_bracket"] = { fg = "#F5F5F4" },
    ["@keyword.function"] = { fg = "#67E8F9", italic = true },
    ["@keyword_but_not_like_that"] = { fg = "#67E8F9", italic = true },
    ["@lsp.type.interface"] = { fg = "#A1E633", underline = true },
    ["@lsp.type.parameter"] = { fg = "#F59F0A", italic = true },
    ["@lsp.type.type"] = { fg = "#A1E633", underline = true },
    ["@lsp.typemod.class.defaultLibrary.typescript"] = { fg = "#67E8F9" },
    ["@lsp.typemod.function.declaration.typescript"] = { fg = "#A1E633" },
    ["@lsp.typemod.function.defaultLibrary"] = { fg = "#67E8F9" },
    ["@punctuation.bracket"] = { fg = "#FCD44F" },
    ["@punctuation.special"] = { fg = "#DB2979" },
    ["@tag"] = { fg = "#67E8F9", italic = true },
    ["@tag.attribute"] = { fg = "#A1E633" },
    ["@tag.builtin"] = { fg = "#DB2979" },
    ["@type"] = { fg = "#F5F5F4" },
    ["@type.builtin"] = { fg = "#67E8F9", italic = true },
    ["@type_annotation_colon"] = { fg = "#DB2979" },
    Comment = { fg = "#78726D" },
    Conditional = { fg = "#DB2979" },
    Constant = { fg = "#A689FA" },
    Delimiter = { fg = "#F5F5F4" },
    DiagnosticError = { fg = "#F43E5C" },
    DiagnosticInfo = { fg = "#22D3EE" },
    DiagnosticUnderlineWarn = { sp = "#FCD34D", undercurl = true },
    DiagnosticWarn = { fg = "#FCD34D" },
    Exception = { fg = "#DB2979" },
    FloatBorder = { fg = "#FCD34D" },
    Function = { fg = "#A1E633" },
    Identifier = { fg = "#F5F5F4" },
    Keyword = { fg = "#DB2979" },
    Label = { fg = "#DB2979" },
    Normal = { bg = "#292524", fg = "#F5F5F4" },
    NormalFloat = { bg = "#292524", fg = "#F5F5F4" },
    Operator = { fg = "#DB2979" },
    Pmenu = { bg = "#292524", fg = "#F5F5F4" },
    PmenuBorder = { fg = "#FCD34D" },
    PmenuExtraBorder = { fg = "#FCD34D" },
    PmenuSel = { bg = "#44403C" },
    PmenuThumb = { bg = "#FCD34D", fg = "#BE185D" },
    RainbowDelimiterBlue = { fg = "#22D3EE" },
    RainbowDelimiterGreen = { fg = "#84CC16" },
    RainbowDelimiterOrange = { fg = "#D97706" },
    RainbowDelimiterPurple = { fg = "#8B5CF6" },
    RainbowDelimiterRed = { fg = "#BE185D" },
    RainbowDelimiterYellow = { fg = "#FCD34D" },
    Repeat = { fg = "#DB2979" },
    SnacksPickerDir = { fg = "#78726D" },
    SnacksPickerListCursorLine = { bg = "#44403C" },
    Special = { fg = "#F5F5F4" },
    String = { fg = "#FDDE6D" },
    Tag = { fg = "#67E8F9" },
    Type = { fg = "#A1E633" },
    WarningMsg = { fg = "#FCD34D" },
}

for group, opts in pairs(highlights) do
    vim.api.nvim_set_hl(0, group, opts)
end
