#!/usr/bin/env bash

. source-if-exists "${HOMEBREW_PREFIX}/etc/bash_completion"

# TODO: move path
. source-if-exists "${HOMEBREW_PREFIX}/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc"
# gcloud/gsutil/etc completions
. source-if-exists "${HOMEBREW_PREFIX}/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc"
