name: validate
on:
  workflow_dispatch: # Manually trigger
  schedule:
    - cron: "0 13 * * 5" # Every Friday at 1pm UTC
jobs:
  validate:
    name: Validate
    strategy:
      matrix:
        os:
          - macos-latest
          # TODO: re-enable once macos is working
          # - ubuntu-latest
          # TODO: add install.ps1 script
          # - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ciiqr/nk-plugins
          path: nk-plugins
      - uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}
      - name: Install
        run: ./install.sh
        working-directory: ${{ github.event.repository.name }}
