name: validate
on:
  workflow_dispatch: # Manually trigger
  schedule:
    - cron: "0 13 * * 5" # Every Friday at 1pm UTC
jobs:
  validate:
    name: Validate
    strategy:
      matrix:
        os:
          - macos-latest
          # TODO: re-enable once macos is working
          # - ubuntu-latest
          # TODO: add install.ps1 script
          # - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ciiqr/nk-plugins
          path: nk-plugins
      - uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}
      - name: Hacks
        run: |
          # my config installs python-yq, which conflicts with the 'yq' package actions runners have installed
          brew unlink yq
          # TODO: pretty sure these exist by default? (if not I'll find out when I setup a fresh machine next)
          mkdir ~/Public ~/Applications
      - name: Install
        run: ./install.sh
        working-directory: ${{ github.event.repository.name }}
